### ISSUE TITLE
Updated ads break array in "listings-bot-old"

### ISSUE THREAD

**Issue by vegedb** [skaiteo/polygran.pac#1]
Apologies for making an issue here and not https://github.com/skaiteo/listings-bot-old since I can't create an issue on a fork.

The site has added a bunch of ads at the 2nd last rows of cards,
After investigating, the array is broken from "undefined" in the output and STOPS the code from running.
This happens to all arrays in **carousell.js**
` const name = element.belowFold[0].stringContent;`
` const price = element.belowFold[1].stringContent;`
` const condition = element.belowFold[3].stringContent;`
` const isBumper = element.aboveFold[0].component === "active_bump"; `

If I remove stringContent, the code will run but break checking

Hope you can help, I can't figure out how to ignore "undefined" in your code.

Example,
![image](https://github.com/skaiteo/polygran.pac/assets/72070424/f5835cf0-a0bf-46d2-936d-f988a237057e)

**Comment by skaiteo** [comment]
Hi, to ignore the banner, you may filter it out with 
`element.type == "BANNER"`.

Do note this repo is no longer being maintained by me so things may be broken.

**Comment by vegedb** [comment]
> Hi, to ignore the banner, you may filter it out with `element.type == "BANNER"`.
> 
> Do note this repo is no longer being maintained by me so things may be broken.

Thanks for replying and showing the right direction.
Banner indeed works
![image](https://github.com/skaiteo/polygran.pac/assets/72070424/4f06ff15-bd52-4b80-9915-353d1b517fa8)


BUT I'm terrible at flatMap, how do you skip the array while filtering out "BANNER" or better yet, let the code continue even if there's a "cut-off" point.
Here is where it **cuts off** looking at console.log(price).
![image](https://github.com/skaiteo/polygran.pac/assets/72070424/ce14ec82-af6c-4a8e-8e3c-1e394287a9c8)

**Comment by skaiteo** [comment]
With flatMap I believe you can just return an empty array `[]`, and it would result in "filtering" out that item. As for letting the code continue, one way is to perhaps wrap the problematic code in a try catch block.

**Comment by vegedb** [comment]
> With flatMap I believe you can just return an empty array `[]`, and it would result in "filtering" out that item. As for letting the code continue, one way is to perhaps wrap the problematic code in a try catch block.

I tried with a simple if statement ,`if (element.type != "BANNER")` ,
It works! and can be seen on console.log.

BUT for the reasons of my lack of flatMap understanding and "return", the undefined reappears as the final result.
Any chance you could help detect the fault here.

![image](https://github.com/skaiteo/polygran.pac/assets/72070424/f64da5ac-190c-4af6-8c65-013a9a4ba1c0)

**Comment by skaiteo** [comment]
That's because by not returning anything when the `if` expression is not met, it returns undefined by default, and `undefined` is still `undefined` after being flattened. What you need is to just add a `return [];` after the `if` statement, so when it **is** a BANNER, it returns an empty array and it gets flattened into nothing:
```
if (element.type != "BANNER") 
  {
    ...
    return [listing];
  }
return [];
```

By the way, if you want, I can help out with your code with pull requests, but not sure if it's possible for you to share a private repository.

**Comment by vegedb** [comment]
> That's because by not returning anything when the `if` expression is not met, it returns undefined by default, and `undefined` is still `undefined` after being flattened. What you need is to just add a `return [];` after the `if` statement, so when it **is** a BANNER, it returns an empty array and it gets flattened into nothing:
> 
> ```
> if (element.type != "BANNER") 
>   {
>     ...
>     return [listing];
>   }
> return [];
> ```
> 
> By the way, if you want, I can help out with your code with pull requests, but not sure if it's possible for you to share a private repository.

Thanks for the help! I managed to get it working by filtering out the output array instead.
`const currenttemp = mapToListings(data);`
 `const currentListings = currenttemp.filter(Boolean);`
